### ISSUE TITLE
Readme Manual

### ISSUE THREAD

**Issue by ahoz** [couchtyp/certbot-dns-schlundtech#1]
Hi,
if i understand right, this plugin could be helpful for renewing wildcard certificates for schlundtech customers. Would you please provide a small manual ?

**Comment by couchtyp** [comment]
Thanks for your interest.
I agree that a small manual in the README would make sense; in the meantime have a look at [`certbot_dns_schlundtech/__init__.py`](https://github.com/couchtyp/certbot-dns-schlundtech/blob/master/certbot_dns_schlundtech/__init__.py), which contains the module documentation, similarly to the official certbot plugins.

**Comment by ahoz** [comment]
Oh, i must have overlooked it.
Thats very helpful. :-)
Thank you very much 👍
