### ISSUE TITLE
Issue wildcard, setup pip modules acme,certbot > 0.22

### ISSUE THREAD

**Issue by janreiche** [couchtyp/certbot-dns-schlundtech#2]
I issued wildcard certs and needed to install newer versions of acme,certbot (>0.22).
Basically edit {{local-oldest-requirements.txt}} and update to actual version 0.26.

**Comment by couchtyp** [comment]
Managing the certbot and acme versions installed on the system is out of scope of this plugin. The local-oldest-requirements.txt and setup.py only specify the *minimum* certbot (and acme) version required to run.

When building the docker container make sure to pull the latest certbot image (docker build --pull) if an outdated image is already available locally.
