### ISSUE TITLE
Release on pypi

### ISSUE THREAD

**Issue by dwt** [couchtyp/certbot-dns-schlundtech#6]
Not sure if I'm missing anything, but it seems you haven't released your package on pypi. This is what I would have assumed to be the project url: <https://pypi.org/project/certbot-dns-schlundtech/> but also with the search function I cannot find anything.

If I can be of any help providing the plugin on pypi, I'd love to assist, as I already have a few packages of my own on pypi.

**Comment by couchtyp** [comment]
You're not missing anything - I simply never came around releasing the project on PyPI.
I'll catch up on that and look into GitHub actions to automate the process ASAP.

**Comment by dwt** [comment]
Looking at your version numbers: 0.03 and 0.04 - you're being quite modest. I would recommend going with 1.0 for the release for certbot 1.0 as your tool is quite mature and it would IMO be good to communicate that in the version number
